# Generated by Django 6.0.2 on 2026-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, help_text='Short English description for this skill', max_length=255),
        ),
    ]
